language: python
sudo: false
python:
- 2.7
before_install:
- export PYTHONPATH=$HOME/.local/lib/python2.7/site-packages/
- pip install pip --upgrade
- pip install nose --upgrade
- pip install six
- pip install -r requirements.txt --upgrade
script: nosetests -s -v
